var dir_d97893c72dedf4e0b2e9e1e8df755fbd =
[
    [ "actualizar_estado_foto.php", "actualizar__estado__foto_8php.html", "actualizar__estado__foto_8php" ],
    [ "conexion.php", "conexion_8php.html", "conexion_8php" ],
    [ "contar_fotos_usuario.php", "contar__fotos__usuario_8php.html", "contar__fotos__usuario_8php" ],
    [ "crear_rally.php", "crear__rally_8php.html", "crear__rally_8php" ],
    [ "delete_usuario.php", "delete__usuario_8php.html", "delete__usuario_8php" ],
    [ "eliminar_foto.php", "eliminar__foto_8php.html", "eliminar__foto_8php" ],
    [ "eliminar_rally.php", "eliminar__rally_8php.html", "eliminar__rally_8php" ],
    [ "estadisticas_admin.php", "estadisticas__admin_8php.html", "estadisticas__admin_8php" ],
    [ "fotos_usuario.php", "fotos__usuario_8php.html", "fotos__usuario_8php" ],
    [ "galeria_fotos.php", "galeria__fotos_8php.html", "galeria__fotos_8php" ],
    [ "ganadores_rallies.php", "ganadores__rallies_8php.html", "ganadores__rallies_8php" ],
    [ "get_fotos_pendientes.php", "get__fotos__pendientes_8php.html", "get__fotos__pendientes_8php" ],
    [ "get_perfil.php", "get__perfil_8php.html", "get__perfil_8php" ],
    [ "get_rallies.php", "get__rallies_8php.html", "get__rallies_8php" ],
    [ "get_usuarios.php", "get__usuarios_8php.html", "get__usuarios_8php" ],
    [ "guardar_comentario.php", "guardar__comentario_8php.html", "guardar__comentario_8php" ],
    [ "listar_rallies.php", "listar__rallies_8php.html", "listar__rallies_8php" ],
    [ "login.php", "login_8php.html", "login_8php" ],
    [ "obtener_comentarios.php", "obtener__comentarios_8php.html", "obtener__comentarios_8php" ],
    [ "quitar_voto.php", "quitar__voto_8php.html", "quitar__voto_8php" ],
    [ "rallies_todos.php", "rallies__todos_8php.html", "rallies__todos_8php" ],
    [ "register.php", "register_8php.html", "register_8php" ],
    [ "subir_foto.php", "subir__foto_8php.html", "subir__foto_8php" ],
    [ "update_perfil.php", "update__perfil_8php.html", "update__perfil_8php" ],
    [ "update_rally.php", "update__rally_8php.html", "update__rally_8php" ],
    [ "update_usuario.php", "update__usuario_8php.html", "update__usuario_8php" ],
    [ "votar_foto.php", "votar__foto_8php.html", "votar__foto_8php" ]
];